Repository LeeKyoungYoung/CRAWebBackend, pull requests merged in 2025-02, with the labels that each got.

#80 [HG]hotfix[#79]: required 옵션 변경
  src/main/java/com/handong/cra/crawebbackend/board/controller/BoardController.java
Labels: fix, hotfix

#86 [CH] feat[#85]: board content img url 유효하게 변경
  build.gradle
  src/main/java/com/handong/cra/crawebbackend/board/domain/Board.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/response/ResListBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/service/BoardServiceImpl.java
  src/main/java/com/handong/cra/crawebbackend/util/BoardMDParser.java
Labels: feat

#102 DTO 파싱 처리 에러 수정
  src/main/java/com/handong/cra/crawebbackend/board/dto/CreateBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/DetailBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/ListBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/response/ResCreateBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/response/ResDetailBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/response/ResListBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/response/ResUpdateBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/service/BoardServiceImpl.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/HavrutaDto.java
Labels: fix

#103 refresh token issue resolving
  src/main/java/com/handong/cra/crawebbackend/auth/controller/AuthController.java
  src/main/java/com/handong/cra/crawebbackend/auth/repository/RefreshTokenRepository.java
  src/main/java/com/handong/cra/crawebbackend/auth/service/AuthService.java
  src/main/java/com/handong/cra/crawebbackend/auth/service/AuthServiceImpl.java
  src/main/java/com/handong/cra/crawebbackend/exception/ErrorCode.java
  src/main/java/com/handong/cra/crawebbackend/exception/auth/AuthInvalidTokenException.java
  src/main/java/com/handong/cra/crawebbackend/exception/auth/AuthTokenExpiredException.java
  src/main/java/com/handong/cra/crawebbackend/item/dto/CreateItemDto.java
  src/main/java/com/handong/cra/crawebbackend/user/dto/UserDetailDto.java
  src/main/java/com/handong/cra/crawebbackend/util/JwtTokenProvider.java
Labels: fix, hotfix

#113 DTO 파싱 수정
  src/main/java/com/handong/cra/crawebbackend/board/dto/response/ResListBoardDto.java
Labels: hotfix

#115 로그인시 기존 존재하는 리프레시 토큰 제거
  src/main/java/com/handong/cra/crawebbackend/auth/service/AuthServiceImpl.java
Labels: hotfix
