Repository LeeKyoungYoung/CRAWebBackend, pull requests merged in 2025-01, with the labels that each got.

#31 Feat/#23
  src/main/java/com/handong/cra/crawebbackend/board/controller/BoardController.java
  src/main/java/com/handong/cra/crawebbackend/board/domain/Board.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/CreateBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/controller/HavrutaController.java
  src/main/java/com/handong/cra/crawebbackend/havruta/domain/Havruta.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/CreateHavrutaDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/DetailHavrutaDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/ListHavrutaDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/UpdateHavrutaDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/request/ReqCreateHavrutaDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/request/ReqUpdateHavrutaDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/response/ResCreateHavrutaDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/response/ResDetailHavrutaDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/response/ResListHavrutaDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/dto/response/ResUpdateHavrutaDto.java
  src/main/java/com/handong/cra/crawebbackend/havruta/repository/HavrutaRepository.java
  src/main/java/com/handong/cra/crawebbackend/havruta/service/HavrutaService.java
  src/main/java/com/handong/cra/crawebbackend/havruta/service/HavrutaServiceImpl.java
Labels: feat

#43 댓글수 보내주는 기능 추가
  src/main/java/com/handong/cra/crawebbackend/comment/controller/CommentController.java
  src/main/java/com/handong/cra/crawebbackend/comment/repository/CommentRepository.java
  src/main/java/com/handong/cra/crawebbackend/comment/service/CommentService.java
  src/main/java/com/handong/cra/crawebbackend/comment/service/CommentServiceImpl.java
Labels: feat

#47 [HG]fix[#34]: id auto generation 옵션 변경
  src/main/java/com/handong/cra/crawebbackend/common/domain/BaseEntity.java
  src/main/java/com/handong/cra/crawebbackend/user/domain/User.java
Labels: fix

#49 보드 리팩터링
  src/main/java/com/handong/cra/crawebbackend/board/controller/BoardController.java
  src/main/java/com/handong/cra/crawebbackend/board/domain/Board.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/CreateBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/DetailBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/ListBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/UpdateBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/request/ReqCreateBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/request/ReqUpdateBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/response/ResCreateBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/response/ResDetailBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/response/ResListBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/dto/response/ResUpdateBoardDto.java
  src/main/java/com/handong/cra/crawebbackend/board/repository/BoardRepository.java
  src/main/java/com/handong/cra/crawebbackend/board/service/BoardService.java
  src/main/java/com/handong/cra/crawebbackend/board/service/BoardServiceImpl.java
  src/main/java/com/handong/cra/crawebbackend/user/domain/User.java
Labels: feat, refactor

#77 image logic fix test
  src/main/java/com/handong/cra/crawebbackend/file/service/S3ImageServiceImpl.java
Labels: test, hotfix
